In [2]:
import pandas as pd
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.metrics import recall_score, classification_report, confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from imblearn.combine import SMOTEENN

In [3]:
df = pd.read_csv('tel_churn.csv')

In [4]:
df.head()

,Unnamed: 0,SeniorCitizen,MonthlyCharges,TotalCharges,Churn,gender_Female,gender_Male,Partner_No,Partner_Yes,Dependents_No,...,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,tenure_group_1 - 12,tenure_group_13 - 24,tenure_group_25 - 36,tenure_group_37 - 48,tenure_group_49 - 60,tenure_group_61 - 72
0,0,0,29.85,29.85,0,1,0,0,1,1,...,0,0,1,0,1,0,0,0,0,0
1,1,0,56.95,1889.50,0,0,1,1,0,1,...,0,0,0,1,0,0,1,0,0,0
2,2,0,53.85,108.15,1,0,1,1,0,1,...,0,0,0,1,1,0,0,0,0,0
3,3,0,42.30,1840.75,0,0,1,1,0,1,...,1,0,0,0,0,0,0,1,0,0
4,4,0,70.70,151.65,1,1,0,1,0,1,...,0,0,1,0,1,0,0,0,0,0

In [5]:
df = df.drop('Unnamed: 0',axis=1)

In [6]:
df.head()

,SeniorCitizen,MonthlyCharges,TotalCharges,Churn,gender_Female,gender_Male,Partner_No,Partner_Yes,Dependents_No,Dependents_Yes,...,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,tenure_group_1 - 12,tenure_group_13 - 24,tenure_group_25 - 36,tenure_group_37 - 48,tenure_group_49 - 60,tenure_group_61 - 72
0,0,29.85,29.85,0,1,0,0,1,1,0,...,0,0,1,0,1,0,0,0,0,0
1,0,56.95,1889.50,0,0,1,1,0,1,0,...,0,0,0,1,0,0,1,0,0,0
2,0,53.85,108.15,1,0,1,1,0,1,0,...,0,0,0,1,1,0,0,0,0,0
3,0,42.30,1840.75,0,0,1,1,0,1,0,...,1,0,0,0,0,0,0,1,0,0
4,0,70.70,151.65,1,1,0,1,0,1,0,...,0,0,1,0,1,0,0,0,0,0

In [8]:
# creating X and Y variables
x = df.drop('Churn' , axis=1)
x

,SeniorCitizen,MonthlyCharges,TotalCharges,gender_Female,gender_Male,Partner_No,Partner_Yes,Dependents_No,Dependents_Yes,PhoneService_No,...,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,tenure_group_1 - 12,tenure_group_13 - 24,tenure_group_25 - 36,tenure_group_37 - 48,tenure_group_49 - 60,tenure_group_61 - 72
0,0,29.85,29.85,1,0,0,1,1,0,1,...,0,0,1,0,1,0,0,0,0,0
1,0,56.95,1889.50,0,1,1,0,1,0,0,...,0,0,0,1,0,0,1,0,0,0
2,0,53.85,108.15,0,1,1,0,1,0,0,...,0,0,0,1,1,0,0,0,0,0
3,0,42.30,1840.75,0,1,1,0,1,0,1,...,1,0,0,0,0,0,0,1,0,0
4,0,70.70,151.65,1,0,1,0,1,0,0,...,0,0,1,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7027,0,84.80,1990.50,0,1,0,1,0,1,0,...,0,0,0,1,0,1,0,0,0,0
7028,0,103.20,7362.90,1,0,0,1,0,1,0,...,0,1,0,0,0,0,0,0,0,1
7029,0,29.60,346.45,1,0,0,1,0,1,1,...,0,0,1,0,1,0,0,0,0,0
7030,1,74.40,306.60,0,1,0,1,1,0,0,...,0,0,0,1,1,0,0,0,0,0
7031,0,105.65,6844.50,0,1,1,0,1,0,0,...,1,0,0,0,0,0,0,0,0,1

In [9]:
y = df['Churn']
y

0       0
1       0
2       1
3       0
4       1
       ..
7027    0
7028    0
7029    0
7030    1
7031    0
Name: Churn, Length: 7032, dtype: int64

In [10]:
x_train , x_test , y_train,y_test = train_test_split(x,y,test_size=0.2)

### Decision Tree Classifier

In [11]:
model_dt = DecisionTreeClassifier(criterion='gini' , random_state=100,max_depth=6,min_samples_split=8)

In [12]:
model_dt.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=6, min_samples_split=8, random_state=100)

In [13]:
y_pred = model_dt.predict(x_test)

In [14]:
y_pred

array([1, 1, 1, ..., 0, 0, 0], shape=(1407,))

In [16]:
print(classification_report(y_test , y_pred , labels = [0,1]))

              precision    recall  f1-score   support

           0       0.84      0.90      0.87      1039
           1       0.64      0.52      0.57       368

    accuracy                           0.80      1407
   macro avg       0.74      0.71      0.72      1407
weighted avg       0.79      0.80      0.79      1407

In [17]:
print(confusion_matrix(y_test , y_pred))

[[933 106]
 [178 190]]

In [20]:
sm = SMOTEENN()
x_resampled, y_resampled = sm.fit_resample(x, y)

In [21]:
xr_train , xr_test , yr_train,yr_test = train_test_split(x_resampled,y_resampled,test_size=0.2)

In [22]:
model_dt_smote = DecisionTreeClassifier(criterion='gini' , random_state=100,max_depth=6,min_samples_split=8)

In [23]:
model_dt_smote.fit(xr_train,yr_train)

DecisionTreeClassifier(max_depth=6, min_samples_split=8, random_state=100)

In [24]:
y_pred_smote = model_dt_smote.predict(xr_test)

In [25]:
print(classification_report(yr_test , y_pred_smote , labels = [0,1]))

              precision    recall  f1-score   support

           0       0.97      0.91      0.94       536
           1       0.93      0.97      0.95       637

    accuracy                           0.94      1173
   macro avg       0.95      0.94      0.94      1173
weighted avg       0.94      0.94      0.94      1173

In [26]:
print(confusion_matrix(yr_test , y_pred_smote))

[[487  49]
 [ 17 620]]

In [27]:
import pickle

In [28]:
filename = 'model.sav'

In [30]:
pickle.dump(model_dt_smote , open(filename , 'wb'))

In [32]:
load_model = pickle.load(open(filename , 'rb'))

In [33]:
load_model.score(xr_test ,yr_test)

0.9437340153452686